export const passions = [
	'90s kid',
	'Harry Potter',
	'SoundCloud',
	'Spa',
	'Self-care',
	'Heavy metal',
	'House parties',
	'Gin & tonic',
	'Gymnastics',
	'Ludo',
	'Maggi',
	'Hot yoga',
	'Biryani',
	'Meditation',
	'Sushi',
	'Spotify',
	'Hockey',
	'Basketball',
	'Slam poetry',
	'Home workouts',
	'Theatre',
	'Café hopping',
	'Trainers',
	'Aquarium',
	'Instagram',
	'Hot springs',
	'Walking',
	'Running',
	'Travel',
	'Language exchange',
	'Films',
	'Guitarists',
	'Social development',
	'Gym',
	'Social media',
	'Hip hop',
	'Skincare',
	'J-Pop',
	'Cricket',
	'Shisha',
	'Freelance',
	'K-Pop',
	'Skateboarding',
	'Gospel',
	'Potterhead',
	'Trying new things',
	'Photography',
	'Bollywood',
	'Bhangra',
	'Reading',
	'Singing',
	'Sports',
	'Poetry',
	'Stand-up comedy',
	'Coffee',
	'Karaoke',
	'Fortnite',
	'Free diving',
	'Self-development',
	'Mental health awareness',
	'Foodie tour',
	'Voter rights',
	'Jiu-jitsu',
	'Climate change',
	'Exhibition',
	'Walking my dog',
	'LGBTQIA+ rights',
	'Feminism',
	'VR room',
	'Escape café',
	'Shopping',
	'Brunch',
	'Investment',
	'Jet skiing',
	'Reggaeton',
	'Vintage clothing',
	'Black Lives Matter',
	'Jogging',
	'Road trips',
	'Vintage fashion',
	'Voguing',
	'Sofa surfing',
	'Happy hour',
	'Inclusivity',
	'Country music',
	'Football',
	'Rollerblading',
	'Investing',
	'Tennis',
	'Ice cream',
	'Ice skating',
	'Human rights',
	'Exhibitions',
	'Pig roast',
	'Skiing',
	'Canoeing',
	'West End musicals',
	'Snowboarding',
	'Pilates',
	'Pentathlon',
	'Broadway',
	'PlayStation',
	'Cheerleading',
	'Choir',
	'Pole dancing',
	'Five-a-side football',
	'Car racing',
	'Pinterest',
	'Festivals',
	'Pub quiz',
	'Catan',
	'Cosplay',
	'Motor sports',
	'Coffee stands',
	'Content creation',
	'E-sports',
	'Bicycle racing',
	'Binge-watching TV series',
	'Songwriter',
	'Bodycombat',
	'Tattoos',
	'Painting',
	'Bodyjam',
	'Paddle boarding',
	'Padel',
	'Blackpink',
	'Surfing',
	'Bowling',
	'Grime',
	'90s Britpop',
	'Bodypump',
	'Beach bars',
	'Bodystep',
	'Paragliding',
	'Upcycling',
	'Equality',
	'Astrology',
	'Motorcycles',
	'Equestrian',
	'Entrepreneurship',
	'Sake',
	'BTS',
	'Cooking',
	'Environmental protection',
	'Fencing',
	'Football',
	'Saxophonist',
	'Sci-fi',
	'Dancing',
	'Film festivals',
	'Freeletics',
	'Gardening',
	'Amateur cook',
	'Exchange programmes',
	'Sauna',
	'Art',
	'Politics',
	'Flamenco',
	'Museum',
	'Activism',
	'DAOs',
	'Real estate',
	'Podcasts',
	'Disability rights',
	'Rave',
	'Pimms',
	'Drive-in cinema',
	'Rock climbing',
	'BBQ',
	'Craft beer',
	'Iced tea',
	'Drummer',
	'Tea',
	'Board games',
	'Roblox',
	'Pubs',
	'Rock',
	'Tango',
	'Drawing',
	'Trivia',
	'Pho',
	'Volunteering',
	'Environmentalism',
	'Rollerskating',
	'Wine',
	'Dungeons & Dragons',
	'Vlogging',
	'Electronic music',
	'Ramen',
	'Weightlifting',
	'Live music',
	'Writing',
	'Xbox',
	'World peace',
]
