import { createSlice } from '@reduxjs/toolkit'
import type { PayloadAction } from '@reduxjs/toolkit'
import type { Photo, RegistrationState } from '@shared/types'

const initialState: RegistrationState = {
	currentStep: 1,
	steps: {
		name: {
			isCompleted: false,
			name: '',
		},
		tags: {
			isCompleted: false,
			selectedTags: [],
			availableTags: [
				'90s kid',
				'Harry Potter',
				'SoundCloud',
				'Spa',
				'Self-care',
				'Heavy metal',
				'House parties',
				'Gin & tonic',
				'Gymnastics',
				'Ludo',
				'Maggi',
				'Hot yoga',
				'Biryani',
				'Meditation',
				'Sushi',
				'Spotify',
				'Hockey',
				'Basketball',
				'Slam poetry',
				'Home workouts',
				'Theatre',
				'Café hopping',
				'Trainers',
				'Aquarium',
				'Instagram',
				'Hot springs',
				'Walking',
				'Running',
				'Travel',
				'Language exchange',
				'Films',
				'Guitarists',
				'Social development',
				'Gym',
				'Social media',
				'Hip hop',
				'Skincare',
				'J-Pop',
				'Cricket',
				'Shisha',
				'Freelance',
				'K-Pop',
				'Skateboarding',
				'Gospel',
				'Potterhead',
				'Trying new things',
				'Photography',
				'Bollywood',
				'Bhangra',
				'Reading',
				'Singing',
				'Sports',
				'Poetry',
				'Stand-up comedy',
				'Coffee',
				'Karaoke',
				'Fortnite',
				'Free diving',
				'Self-development',
				'Mental health awareness',
				'Foodie tour',
				'Voter rights',
				'Jiu-jitsu',
				'Climate change',
				'Exhibition',
				'Walking my dog',
				'LGBTQIA+ rights',
				'Feminism',
				'VR room',
				'Escape café',
				'Shopping',
				'Brunch',
				'Investment',
				'Jet skiing',
				'Reggaeton',
				'Vintage clothing',
				'Black Lives Matter',
				'Jogging',
				'Road trips',
				'Vintage fashion',
				'Voguing',
				'Sofa surfing',
				'Happy hour',
				'Inclusivity',
				'Country music',
				'Football',
				'Rollerblading',
				'Investing',
				'Tennis',
				'Ice cream',
				'Ice skating',
				'Human rights',
				'Exhibitions',
				'Pig roast',
				'Skiing',
				'Canoeing',
				'West End musicals',
				'Snowboarding',
				'Pilates',
				'Pentathlon',
				'Broadway',
				'PlayStation',
				'Cheerleading',
				'Choir',
				'Pole dancing',
				'Five-a-side football',
				'Car racing',
				'Pinterest',
				'Festivals',
				'Pub quiz',
				'Catan',
				'Cosplay',
				'Motor sports',
				'Coffee stands',
				'Content creation',
				'E-sports',
				'Bicycle racing',
				'Binge-watching TV series',
				'Songwriter',
				'Bodycombat',
				'Tattoos',
				'Painting',
				'Bodyjam',
				'Paddle boarding',
				'Padel',
				'Blackpink',
				'Surfing',
				'Bowling',
				'Grime',
				'90s Britpop',
				'Bodypump',
				'Beach bars',
				'Bodystep',
				'Paragliding',
				'Upcycling',
				'Equality',
				'Astrology',
				'Motorcycles',
				'Equestrian',
				'Entrepreneurship',
				'Sake',
				'BTS',
				'Cooking',
				'Environmental protection',
				'Fencing',
				'Football',
				'Saxophonist',
				'Sci-fi',
				'Dancing',
				'Film festivals',
				'Freeletics',
				'Gardening',
				'Amateur cook',
				'Exchange programmes',
				'Sauna',
				'Art',
				'Politics',
				'Flamenco',
				'Museum',
				'Activism',
				'DAOs',
				'Real estate',
				'Podcasts',
				'Disability rights',
				'Rave',
				'Pimms',
				'Drive-in cinema',
				'Rock climbing',
				'BBQ',
				'Craft beer',
				'Iced tea',
				'Drummer',
				'Tea',
				'Board games',
				'Roblox',
				'Pubs',
				'Rock',
				'Tango',
				'Drawing',
				'Trivia',
				'Pho',
				'Volunteering',
				'Environmentalism',
				'Rollerskating',
				'Wine',
				'Dungeons & Dragons',
				'Vlogging',
				'Electronic music',
				'Ramen',
				'Weightlifting',
				'Live music',
				'Writing',
				'Xbox',
				'World peace',
				'Wrestling',
				'Literature',
				'Manga',
				'Pride',
				'Marathon',
				'Make-up',
				'Youth empowerment',
				'YouTube',
				'Martial arts',
				'Marvel',
				'Vegan cooking',
				'Vermouth',
				'Korean food',
				'Twitter',
				'Volleyball',
				'Walking tours',
				'Vinyasa',
				'Virtual reality',
				'League of Legends',
				'NFTs',
				'Pub crawls',
				'Nintendo',
				'Baseball',
				'Parties',
				'Ballet',
				'Bands',
				'Online games',
				'Battle Ground',
				'Beach tennis',
				'Nightlife',
				'Online shopping',
				'Sailing',
				'Olympic gymnastics',
				'Bassist',
				'Online broker',
				'Military',
				'Memes',
				'Among Us',
				'Motorbike racing',
				'Motorcycling',
				'Metaverse',
				'Mindfulness',
				'Acapella',
				'Playing a musical instrument',
				'Art galleries',
				'Writing musicals',
				'Hiking',
				'Artistic gymnastics',
				'Mountains',
				'Archery',
				'Atari',
				'Backpacking',
				'Fishing',
				'Clubbing',
				'Street food',
				'Crossfit',
				'Concerts',
				'Climbing',
				'Baking',
				'Camping',
				'Blogging',
				'Collecting',
				'Cars',
				'Start-ups',
				'Boba tea',
				'High-school baseketball league (TW)',
				'Badminton',
				'Active lifestyle',
				'Fashion',
				'Anime',
				'NBA',
				'MLB',
				'Funk music',
				'Caipirinha',
				'Indoor activities',
				'Tempeh',
				'DIY',
				'Town festivities',
				'Cycling',
				'Outdoors',
				'TikTok',
				'Picnicking',
				'Twitch',
				'Comedy',
				'Trap music',
				'Music',
				'Triathlon',
				'Netflix',
				'Disney',
				'Rugby',
				'Açaí',
				'Samba',
				'Tarot',
				'Stock exchange',
				'Stocks',
				'Swimming',
				'Table tennis',
				'Killing time',
				'Working out',
				'Yoga',
				'Horror films',
				'Boxing',
				'Chilling at a bar',
			],
		},
		photos: {
			isCompleted: false,
			photos: [],
		},
	},
}

const registrationSlice = createSlice({
	name: 'registration',
	initialState,
	reducers: {
		setCurrentStep: (state, action: PayloadAction<number>) => {
			state.currentStep = action.payload
		},
		nextStep: state => {
			if (state.currentStep < 3) {
				state.currentStep += 1
			}
		},
		prevStep: state => {
			if (state.currentStep > 1) {
				state.currentStep -= 1
			}
		},
		updateNameStep: (
			state,
			action: PayloadAction<{
				name?: string
			}>
		) => {
			state.steps.name = { ...state.steps.name, ...action.payload }
			const { name } = state.steps.name
			state.steps.name.isCompleted = !!name
		},
		updateTagsStep: (
			state,
			action: PayloadAction<{ selectedTags: string[] }>
		) => {
			state.steps.tags.selectedTags = action.payload.selectedTags
			state.steps.tags.isCompleted = action.payload.selectedTags.length > 0
		},
		addTag: (state, action: PayloadAction<string>) => {
			const tag = action.payload
			const selectedTags = state.steps.tags.selectedTags
			if (!selectedTags.includes(tag)) {
				selectedTags.push(tag)
				state.steps.tags.isCompleted = selectedTags.length > 0
			}
		},
		removeTag: (state, action: PayloadAction<string>) => {
			const tag = action.payload
			const selectedTags = state.steps.tags.selectedTags
			const index = selectedTags.indexOf(tag)
			if (index > -1) {
				selectedTags.splice(index, 1)
				state.steps.tags.isCompleted = selectedTags.length > 0
			}
		},
		addPhoto: (state, action: PayloadAction<Photo>) => {
			state.steps.photos.photos.push(action.payload)
			state.steps.photos.isCompleted = state.steps.photos.photos.length > 0
		},
		removePhoto: (state, action: PayloadAction<Photo>) => {
			const photos = state.steps.photos.photos
			const index = photos.findIndex(photo => photo.id === action.payload.id)

			if (index > -1) {
				photos.splice(index, 1)
				state.steps.photos.isCompleted = photos.length > 0
			}
		},
	},
})

export const {
	setCurrentStep,
	nextStep,
	prevStep,
	updateNameStep,
	updateTagsStep,
	addTag,
	removeTag,
	addPhoto,
	removePhoto,
} = registrationSlice.actions

export default registrationSlice.reducer
